'use strict'
const makePaymentPage = require('../pageobjects/make-payment.js')
const ivoryS10Page = require('../pageobjects/s10-page.js')

describe('10%Ivory', function () {
    it("AC-1 S10 - 10%Ivory", async () => {
      await browser.url('/')
      await makePaymentPage.selecthowcertainRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectwhatTypeOfItemIsIt2RadioRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.clickOnUploadBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
      await ivoryS10Page.enterwhereIsIvory('necklace')
      await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
      await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryVolumeRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryIsIntegralRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryAge7oRadioBtn()
      await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectdoYouOwnTheItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enterFullnamesDetails('test')
      await makePaymentPage.enterEmailAddress('test@test.com')
      await makePaymentPage.confirmEmailAdress('test@test.com') 
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enteraddressNameorNumber('6')
      await makePaymentPage.enterAddressPostcode('BS16 2LL')
      await makePaymentPage.clickOnFindAddressButton() 
      await makePaymentPage.clickOnConfirmAndContinue()
      await makePaymentPage.selectintentionForItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.checkDeclarationCheckbox()
      await makePaymentPage.clickOnSubmitAfterAgreement()
      await makePaymentPage.enterCardNumberDetails('4444333322221111')
      await makePaymentPage.enterExpiryMonth('01')
      await makePaymentPage.enterExpiryYear('23')
      await makePaymentPage.entercardholderName('test')
      await makePaymentPage.entercvcNumber('123')
      await makePaymentPage.enteraddressLine1('10 satin drive')
      await makePaymentPage.enterACity('Manchester')
      await makePaymentPage.enterpostcode('m97bq')
      await makePaymentPage.clicksubmitPayment()
      await makePaymentPage.clickconfirmPayment()
      await expect(makePaymentPage.pageHeaderOne).toHaveText('Self-declaration complete')

    })
    it("AC-2 S10 - 10%Ivory", async () => {
      await browser.url('/')
      await makePaymentPage.selecthowcertainRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectwhatTypeOfItemIsIt4RadioRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.clickOnUploadBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
      await ivoryS10Page.enterwhereIsIvory('necklace')
      await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
      await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectdoYouOwnTheItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enterFullnamesDetails('test')
      await makePaymentPage.enterEmailAddress('test@test.com')
      await makePaymentPage.confirmEmailAdress('test@test.com') 
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enteraddressNameorNumber('6')
      await makePaymentPage.enterAddressPostcode('BS16 2LL')
      await makePaymentPage.clickOnFindAddressButton() 
      await makePaymentPage.clickOnConfirmAndContinue()
      await makePaymentPage.selectintentionForItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.checkDeclarationCheckbox()
      await makePaymentPage.clickOnSubmitAfterAgreement()
      await makePaymentPage.enterCardNumberDetails('4444333322221111')
      await makePaymentPage.enterExpiryMonth('01')
      await makePaymentPage.enterExpiryYear('23')
      await makePaymentPage.entercardholderName('test')
      await makePaymentPage.entercvcNumber('123')
      await makePaymentPage.enteraddressLine1('10 satin drive')
      await makePaymentPage.enterACity('Manchester')
      await makePaymentPage.enterpostcode('m97bq')
      await makePaymentPage.clicksubmitPayment()
      await makePaymentPage.clickconfirmPayment()
      await expect(makePaymentPage.pageHeaderOne).toHaveText('Self-declaration complete')

    })
    it("AC-3 S10 - 10%Ivory", async () => {
      await browser.url('/')
      await makePaymentPage.selecthowcertainRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectwhatTypeOfItemIsIt2RadioRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.clickOnUploadBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
      await ivoryS10Page.enterwhereIsIvory('necklace')
      await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
      await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryVolumeRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryIsIntegralRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryAge7oRadioBtn()
      await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectdoYouOwnTheItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enterFullnamesDetails('test')
      await makePaymentPage.enterEmailAddress('test@test.com')
      await makePaymentPage.confirmEmailAdress('test@test.com') 
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enteraddressNameorNumber('6')
      await makePaymentPage.enterAddressPostcode('BS16 2LL')
      await makePaymentPage.clickOnFindAddressButton() 
      await makePaymentPage.clickOnConfirmAndContinue()
      await makePaymentPage.selectintentionForItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.checkDeclarationCheckbox()
      await makePaymentPage.clickOnSubmitAfterAgreement()
      await makePaymentPage.enterCardNumberDetails('4444333322221111')
      await makePaymentPage.enterExpiryMonth('01')
      await makePaymentPage.enterExpiryYear('23')
      await makePaymentPage.entercardholderName('test')
      await makePaymentPage.entercvcNumber('123')
      await makePaymentPage.enteraddressLine1('10 satin drive')
      await makePaymentPage.enterACity('Manchester')
      await makePaymentPage.enterpostcode('m97bq')
      await makePaymentPage.clicksubmitPayment()
      await makePaymentPage.clickconfirmPayment()
      await expect(makePaymentPage.pageHeaderOne).toHaveText('Self-declaration complete')
  })
  it("AC-4 S10 - 10%Ivory", async () => {
    await browser.url('/')
    await makePaymentPage.selecthowcertainRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectwhatTypeOfItemIsIt3RadioRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.clickOnUploadBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
    await ivoryS10Page.enterwhereIsIvory('necklace')
    await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
    await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectivoryAge7oRadioBtn()
    await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectdoYouOwnTheItemRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.enterFullnamesDetails('test')
    await makePaymentPage.enterEmailAddress('test@test.com')
    await makePaymentPage.confirmEmailAdress('test@test.com') 
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.enteraddressNameorNumber('6')
    await makePaymentPage.enterAddressPostcode('BS16 2LL')
    await makePaymentPage.clickOnFindAddressButton() 
    await makePaymentPage.clickOnConfirmAndContinue()
    await makePaymentPage.selectintentionForItemRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.checkDeclarationCheckbox()
    await makePaymentPage.clickOnSubmitAfterAgreement()
    await makePaymentPage.enterCardNumberDetails('4444333322221111')
    await makePaymentPage.enterExpiryMonth('01')
    await makePaymentPage.enterExpiryYear('23')
    await makePaymentPage.entercardholderName('test')
    await makePaymentPage.entercvcNumber('123')
    await makePaymentPage.enteraddressLine1('10 satin drive')
    await makePaymentPage.enterACity('Manchester')
    await makePaymentPage.enterpostcode('m97bq')
    await makePaymentPage.clicksubmitPayment()
    await makePaymentPage.clickconfirmPayment()
    await expect(makePaymentPage.pageHeaderOne).toHaveText('Self-declaration complete')

  })
  it("AC-5 S10 - 10%Ivory", async () => {
    await browser.url('/')
    await makePaymentPage.selecthowcertainRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectwhatTypeOfItemIsIt2RadioRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.clickOnUploadBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
    await ivoryS10Page.enterwhereIsIvory('necklace')
    await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
    await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectivoryVolumeRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectivoryIsIntegralRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectivoryAge7oRadioBtn()
    await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
    await makePaymentPage.clickContinueBtn()
    await ivoryS10Page.selectdoYouOwnTheItemRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.enterFullnamesDetails('test')
    await makePaymentPage.enterEmailAddress('test@test.com')
    await makePaymentPage.confirmEmailAdress('test@test.com') 
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.enteraddressNameorNumber('6')
    await makePaymentPage.enterAddressPostcode('BS16 2LL')
    await makePaymentPage.clickOnFindAddressButton() 
    await makePaymentPage.clickOnConfirmAndContinue()
    await makePaymentPage.selectintentionForItemRadioBtn()
    await makePaymentPage.clickContinueBtn()
    await makePaymentPage.checkDeclarationCheckbox()
    await makePaymentPage.clickOnSubmitAfterAgreement()
    await makePaymentPage.enterCardNumberDetails('4444333322221111')
    await makePaymentPage.enterExpiryMonth('01')
    await makePaymentPage.enterExpiryYear('23')
    await makePaymentPage.entercardholderName('test')
    await makePaymentPage.entercvcNumber('123')
    await makePaymentPage.enteraddressLine1('10 satin drive')
    await makePaymentPage.enterACity('Manchester')
    await makePaymentPage.enterpostcode('m97bq')
    await makePaymentPage.clicksubmitPayment()
    await makePaymentPage.clickconfirmPayment()
    await expect(makePaymentPage.pageHeaderOne).toHaveText('Self-declaration complete')

  })
})


