'use strict'
const makePaymentPage = require('../pageobjects/make-payment.js')
const ivoryS10Page = require('../pageobjects/s10-page.js')

describe('Revoke certificate', function () {
    it("AC-1 Revoke certificate", async () => {
      await browser.url('/')
      await makePaymentPage.selecthowcertainRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.selectRmiItemFive()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.selectwhatTypeOfItemIsItRadioBtn()
      await makePaymentPage.enterCertNumberToRevoke()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.revokeCertNumber('AB12CD34')
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.clickOnUploadBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
      await ivoryS10Page.enterwhereIsIvory('necklace')
      await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
      await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
      await ivoryS10Page.enterwhereMade('japan')
      await ivoryS10Page.enterwhenMadeRadio('italy')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.enterwhyRmi('test')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.selectivoryAge8oRadioBtn()
      await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
      await makePaymentPage.clickContinueBtn()
      await ivoryS10Page.wantToAddDocuments2Radio()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.clickOnselectdoYouOwnTheItem()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enterFullnamesDetails('test')
      await makePaymentPage.enterEmailAddress('test@test.com')
      await makePaymentPage.confirmEmailAdress('test@test.com') 
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.enteraddressNameorNumber('6')
      await makePaymentPage.enterAddressPostcode('BS16 2LL')
      await makePaymentPage.clickOnFindAddressButton() 
      await makePaymentPage.clickOnConfirmAndContinue()
      await makePaymentPage.selectintentionForItemRadioBtn()
      await makePaymentPage.clickContinueBtn()
      await makePaymentPage.checkDeclarationCheckbox()
      await makePaymentPage.clickOnSubmitAfterAgreement()
      await makePaymentPage.selectsubmitAfterAgreementRadioBtn()
      await makePaymentPage.clickOnSubmitAfterAgreement()
      await makePaymentPage.enterCardNumberDetails('4444333322221111')
      await makePaymentPage.enterExpiryMonth('01')
      await makePaymentPage.enterExpiryYear('23')
      await makePaymentPage.entercardholderName('test')
      await makePaymentPage.entercvcNumber('123')
      await makePaymentPage.enteraddressLine1('10 satin drive')
      await makePaymentPage.enterACity('Manchester')
      await makePaymentPage.enterpostcode('m97bq')
      await makePaymentPage.clicksubmitPayment()
      await makePaymentPage.clickconfirmPayment()
      await expect(makePaymentPage.pageHeaderOne).toHaveText('Application received')
    })
      it("AC-2 Revoke certificate", async () => {
        await browser.url('/')
        await makePaymentPage.selecthowcertainRadioBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.selectRmiItemFive()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.selectnowhatTypeOfItemIsItRadioBtn()
        // await makePaymentPage.enterCertNumberToRevoke()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickonappliedBefore2()
        // await makePaymentPage.revokeCertNumber('AB12CD34')
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.clickOnUploadBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickContinueBtn()
        // await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
        await ivoryS10Page.enterwhereIsIvory('necklace')
        await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
        await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
        await ivoryS10Page.enterwhereMade('japan')
        await ivoryS10Page.enterwhenMadeRadio('italy')
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.enterwhyRmi('test')
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.selectivoryAge8oRadioBtn()
        await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.wantToAddDocuments2Radio()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickOnselectdoYouOwnTheItem()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.enterFullnamesDetails('test')
        await makePaymentPage.enterEmailAddress('test@test.com')
        await makePaymentPage.confirmEmailAdress('test@test.com') 
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.enteraddressNameorNumber('6')
        await makePaymentPage.enterAddressPostcode('BS16 2LL')
        await makePaymentPage.clickOnFindAddressButton() 
        await makePaymentPage.clickOnConfirmAndContinue()
        await makePaymentPage.selectintentionForItemRadioBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.checkDeclarationCheckbox()
        await makePaymentPage.clickOnSubmitAfterAgreement()
        await makePaymentPage.selectsubmitAfterAgreementRadioBtn()
        await makePaymentPage.clickOnSubmitAfterAgreement()
        await makePaymentPage.enterCardNumberDetails('4444333322221111')
        await makePaymentPage.enterExpiryMonth('01')
        await makePaymentPage.enterExpiryYear('23')
        await makePaymentPage.entercardholderName('test')
        await makePaymentPage.entercvcNumber('123')
        await makePaymentPage.enteraddressLine1('10 satin drive')
        await makePaymentPage.enterACity('Manchester')
        await makePaymentPage.enterpostcode('m97bq')
        await makePaymentPage.clicksubmitPayment()
        await makePaymentPage.clickconfirmPayment()
        await expect(makePaymentPage.pageHeaderOne).toHaveText('Application received')
      })
      it("AC-3 Revoke certificate", async () => {
        await browser.url('/')
        await makePaymentPage.selecthowcertainRadioBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.selectRmiItemFive()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.selectwhatTypeOfItemIsItRadioBtn()
        await makePaymentPage.enterCertNumberToRevoke()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.revokeCertNumber('AB12CD34')
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.clickOnUploadBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickContinueBtn()
        // await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
        await ivoryS10Page.enterwhereIsIvory('necklace')
        await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
        await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
        await ivoryS10Page.enterwhereMade('japan')
        await ivoryS10Page.enterwhenMadeRadio('italy')
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.enterwhyRmi('test')
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.selectivoryAge8oRadioBtn()
        await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
        await makePaymentPage.clickContinueBtn()
        await ivoryS10Page.wantToAddDocuments2Radio()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.clickOnselectdoYouOwnTheItem()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.enterFullnamesDetails('test')
        await makePaymentPage.enterEmailAddress('test@test.com')
        await makePaymentPage.confirmEmailAdress('test@test.com') 
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.enteraddressNameorNumber('6')
        await makePaymentPage.enterAddressPostcode('BS16 2LL')
        await makePaymentPage.clickOnFindAddressButton() 
        await makePaymentPage.clickOnConfirmAndContinue()
        await makePaymentPage.selectintentionForItemRadioBtn()
        await makePaymentPage.clickContinueBtn()
        await makePaymentPage.checkDeclarationCheckbox()
        await makePaymentPage.clickOnSubmitAfterAgreement()
        await makePaymentPage.selectsubmitAfterAgreementRadioBtn()
        await makePaymentPage.clickOnSubmitAfterAgreement()
        await makePaymentPage.enterCardNumberDetails('4444333322221111')
        await makePaymentPage.enterExpiryMonth('01')
        await makePaymentPage.enterExpiryYear('23')
        await makePaymentPage.entercardholderName('test')
        await makePaymentPage.entercvcNumber('123')
        await makePaymentPage.enteraddressLine1('10 satin drive')
        await makePaymentPage.enterACity('Manchester')
        await makePaymentPage.enterpostcode('m97bq')
        await makePaymentPage.clicksubmitPayment()
        await makePaymentPage.clickconfirmPayment()
        await expect(makePaymentPage.pageHeaderOne).toHaveText('Application received')
      })
        it("AC-4 Revoke certificate", async () => {
          await browser.url('/')
          await makePaymentPage.selecthowcertainRadioBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.selectRmiItemFive()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.selectnowhatTypeOfItemIsItRadioBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickonappliedBefore()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.enterpreviousApplicationNumber('AB12CD34')
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.clickOnUploadBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
          await ivoryS10Page.enterwhereIsIvory('necklace')
          await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
          await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
          await ivoryS10Page.enterwhereMade('japan')
          await ivoryS10Page.enterwhenMadeRadio('italy')
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.enterwhyRmi('test')
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.selectivoryAge8oRadioBtn()
          await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.wantToAddDocuments2Radio()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickOnselectdoYouOwnTheItem()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.enterFullnamesDetails('test')
          await makePaymentPage.enterEmailAddress('test@test.com')
          await makePaymentPage.confirmEmailAdress('test@test.com') 
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.enteraddressNameorNumber('6')
          await makePaymentPage.enterAddressPostcode('BS16 2LL')
          await makePaymentPage.clickOnFindAddressButton() 
          await makePaymentPage.clickOnConfirmAndContinue()
          await makePaymentPage.selectintentionForItemRadioBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.checkDeclarationCheckbox()
          await makePaymentPage.clickOnSubmitAfterAgreement()
          await makePaymentPage.selectsubmitAfterAgreementRadioBtn()
          await makePaymentPage.clickOnSubmitAfterAgreement()
          await makePaymentPage.enterCardNumberDetails('4444333322221111')
          await makePaymentPage.enterExpiryMonth('01')
          await makePaymentPage.enterExpiryYear('23')
          await makePaymentPage.entercardholderName('test')
          await makePaymentPage.entercvcNumber('123')
          await makePaymentPage.enteraddressLine1('10 satin drive')
          await makePaymentPage.enterACity('Manchester')
          await makePaymentPage.enterpostcode('m97bq')
          await makePaymentPage.clicksubmitPayment()
          await makePaymentPage.clickconfirmPayment()
          await expect(makePaymentPage.pageHeaderOne).toHaveText('Application received')
        })
        it("AC-5 Revoke certificate", async () => {
          await browser.url('/')
          await makePaymentPage.selecthowcertainRadioBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.selectRmiItemFive()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickonappliedBefore3()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.revokeCertNumber('AB12CD34')
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.clickOnUploadBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.enterwhatIsItem('Ivory jewellery')
          await ivoryS10Page.enterwhereIsIvory('necklace')
          await ivoryS10Page.selecthasDistinguishingFeaturesRadioBtn()
          await ivoryS10Page.enterdistinguishingFeatures('very unique 15th century item')
          await ivoryS10Page.enterwhereMade('japan')
          await ivoryS10Page.enterwhenMadeRadio('italy')
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.enterwhyRmi('test')
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.selectivoryAge8oRadioBtn()
          await ivoryS10Page.selectotherReasonRadioBtn('I have so many reasons')
          await makePaymentPage.clickContinueBtn()
          await ivoryS10Page.wantToAddDocuments2Radio()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.clickOnselectdoYouOwnTheItem()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.enterFullnamesDetails('test')
          await makePaymentPage.enterEmailAddress('test@test.com')
          await makePaymentPage.confirmEmailAdress('test@test.com') 
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.enteraddressNameorNumber('6')
          await makePaymentPage.enterAddressPostcode('BS16 2LL')
          await makePaymentPage.clickOnFindAddressButton() 
          await makePaymentPage.clickOnConfirmAndContinue()
          await makePaymentPage.selectintentionForItemRadioBtn()
          await makePaymentPage.clickContinueBtn()
          await makePaymentPage.checkDeclarationCheckbox()
          await makePaymentPage.clickOnSubmitAfterAgreement()
          await makePaymentPage.selectsubmitAfterAgreementRadioBtn()
          await makePaymentPage.clickOnSubmitAfterAgreement()
          await makePaymentPage.enterCardNumberDetails('4444333322221111')
          await makePaymentPage.enterExpiryMonth('01')
          await makePaymentPage.enterExpiryYear('23')
          await makePaymentPage.entercardholderName('test')
          await makePaymentPage.entercvcNumber('123')
          await makePaymentPage.enteraddressLine1('10 satin drive')
          await makePaymentPage.enterACity('Manchester')
          await makePaymentPage.enterpostcode('m97bq')
          await makePaymentPage.clicksubmitPayment()
          await makePaymentPage.clickconfirmPayment()
          await expect(makePaymentPage.pageHeaderOne).toHaveText('Application received')
        })
    })

